//  This file was generated by LevelHelper
//  http://www.levelhelper.org
//
//  LevelHelperLoader.h
//  Created by Bogdan Vladu
//  Copyright 2011 Bogdan Vladu. All rights reserved.
//
////////////////////////////////////////////////////////////////////////////////
//
//  This software is provided 'as-is', without any express or implied
//  warranty.  In no event will the authors be held liable for any damages
//  arising from the use of this software.
//  Permission is granted to anyone to use this software for any purpose,
//  including commercial applications, and to alter it and redistribute it
//  freely, subject to the following restrictions:
//  The origin of this software must not be misrepresented; you must not
//  claim that you wrote the original software. If you use this software
//  in a product, an acknowledgment in the product documentation would be
//  appreciated but is not required.
//  Altered source versions must be plainly marked as such, and must not be
//  misrepresented as being the original software.
//  This notice may not be removed or altered from any source distribution.
//  By "software" the author refers to this code file and not the application 
//  that was used to generate this file.
//
////////////////////////////////////////////////////////////////////////////////

#import "LevelHelperLoader.h"
@interface LevelHelperLoader (SPRITE_INFO_EXTENSION) 

//this methods will return nil if fail
+(NSString*) uniqueNameForSprite:(LHSprite*)sprite;
+(NSString*) uniqueNameForBody:(b2Body*)body;

//value must be a NSObject type
+(void) setCustomValue:(id)value withKey:(NSString*)key onSprite:(LHSprite*)spritey;
+(id) customValueWithKey:(NSString*)key forSprite:(LHSprite*)spritey;
//------------------------------------------------------------------------------
//if fail will return -1
+(int) tagForSprite:(LHSprite*)spritey;
//if fail will return -1
+(int) tagForBody:(b2Body*)body;
//------------------------------------------------------------------------------
+(b2Body*) bodyForSprite:(LHSprite*)spritey;
//if fail will return nil
+(LHSprite*) spriteForBody:(b2Body*)body;
//------------------------------------------------------------------------------

//example of use
/*
 NSArray* arr = [lh bodiesWithTag:YOUR TAG];
 for(NSValue* val in arr)
 {
 b2Body* body = [val pointerValue];
 ...
 }
 */
-(NSArray*) bodiesWithTag:(enum LevelHelper_TAG)tag;
-(b2Body*) bodyWithUniqueName:(NSString*)name;


-(bool) removeSpriteWithUniqueName:(NSString*)name;
-(bool) removeBodyWithUniqueName:(NSString*)name;

-(bool) removeBody:(b2Body*)body;
-(bool) removeBodiesWithTag:(enum LevelHelper_TAG)tag;
-(bool) removeAllBodies;


-(bool) removeBodyWithUniqueName:(NSString*)name;
-(bool) removeSpriteWithUniqueName:(NSString*)name;

@end	
