//  This file was generated by LevelHelper
//  http://www.levelhelper.org
//
//  LevelHelperLoader.h
//  Created by Bogdan Vladu
//  Copyright 2011 Bogdan Vladu. All rights reserved.
//
////////////////////////////////////////////////////////////////////////////////
//
//  This software is provided 'as-is', without any express or implied
//  warranty.  In no event will the authors be held liable for any damages
//  arising from the use of this software.
//  Permission is granted to anyone to use this software for any purpose,
//  including commercial applications, and to alter it and redistribute it
//  freely, subject to the following restrictions:
//  The origin of this software must not be misrepresented; you must not
//  claim that you wrote the original software. If you use this software
//  in a product, an acknowledgment in the product documentation would be
//  appreciated but is not required.
//  Altered source versions must be plainly marked as such, and must not be
//  misrepresented as being the original software.
//  This notice may not be removed or altered from any source distribution.
//  By "software" the author refers to this code file and not the application 
//  that was used to generate this file.
//
////////////////////////////////////////////////////////////////////////////////

#import <Foundation/Foundation.h>
#import "cocos2d.h"
#include "Box2D.h"

@class LHPathNode;
@class LHAnimationNode;
@interface LHSprite : CCSprite
{
	b2Body* body; //week ptr
    NSMutableString* uniqueName;
    NSMutableDictionary* customUserValues;
    
    int currentFrame;
    LHAnimationNode* animation;
    LHPathNode* pathNode;
}

+(id) spriteWithTexture:(CCTexture2D*)texture;
+(id) spriteWithTexture:(CCTexture2D*)texture rect:(CGRect)rect;
+(id) spriteWithSpriteFrame:(CCSpriteFrame*)spriteFrame;
+(id) spriteWithSpriteFrameName:(NSString*)spriteFrameName;
+(id) spriteWithFile:(NSString*)filename;
+(id) spriteWithFile:(NSString*)filename rect:(CGRect)rect;
+(id) spriteWithCGImage: (CGImageRef)image key:(NSString*)key;
+(id) spriteWithBatchNode:(CCSpriteBatchNode*)batchNode rect:(CGRect)rect;

-(id) initWithTexture:(CCTexture2D*)texture;
-(id) initWithTexture:(CCTexture2D*)texture rect:(CGRect)rect;
-(id) initWithSpriteFrame:(CCSpriteFrame*)spriteFrame;
-(id) initWithSpriteFrameName:(NSString*)spriteFrameName;
-(id) initWithFile:(NSString*)filename;
-(id) initWithFile:(NSString*)filename rect:(CGRect)rect;
-(id) initWithCGImage:(CGImageRef)image key:(NSString*)key;
-(id) initWithBatchNode:(CCSpriteBatchNode*)batchNode rect:(CGRect)rect;
-(id) initWithBatchNode:(CCSpriteBatchNode*)batchNode rectInPixels:(CGRect)rect;

////////////////////////////////////////////////////////////////////////////////
-(void) setUniqueName:(NSString*)name;
-(NSString*)uniqueName;

-(void) setBody:(b2Body*)body;
-(b2Body*)body;
-(bool) removeBodyFromWorld;

-(void) setAnimation:(LHAnimationNode*)anim;
-(LHAnimationNode*)animation;
-(NSString*) animationName;
-(int) numberOfFrames;

-(void) setFrame:(int)frmNo;
-(int) currentFrame;

-(void) setPathNode:(LHPathNode*)node;
-(LHPathNode*)pathNode;

-(void) setCustomValue:(id)value withKey:(NSString*)key;
-(id) customValueWithKey:(NSString*)key;
@end	
